print("Привет 'Все'")
print('Привет "Все"')
print('привет!!!')
print('Приветище!!!')
print("Hallo!")
print("Hallo")
print("Hi")
print("How are you?")
print("How do you do?")
print("I study in netology")
